### PR TITLE
Added Hesby's additions to recap

### PR DESCRIPTION
**Pull request by MattHesby**
Comments based on adding to what is currently in the recap.  Further meeting should provide more in depth analysis of +/- specifically looking at curriculum and education moves that club leaders can make.

### CODE REVIEW

**Comment by MaxWofford** [comment]
Thanks for the contribution @MattHesby! Would you please wrap the lines at 80 characters?

**Comment by zachlatta** [comment]
Latest commit looks good to me!

**Comment by MaxWofford** [comment]
Thanks for the pull request @MattHesby!

**Comment by zachlatta** [comment]
🎉🎉🎉

--
Zach Latta
Hack Club | zach@hackclub.io

**Comment by MaxWofford** [comment]
I... wat?

**Comment by MaxWofford** [comment]
Oh, for some reason that comment zalgoed while it was loading.

**Pull request merged**
