### PR TITLE
Rename onboarding protocol to staff onboarding

### PR DESCRIPTION
**Pull request by MaxWofford**

### CODE REVIEW

**Comment by paked** [comment]
lgtm

**Comment by MaxWofford** [comment]
@paked Would you like to merge this?

**Comment by zachlatta** [comment]
:heart: @paked

**Comment by zachlatta** [comment]
Oh snap, I didn't see that @MaxWofford assigned you. So sorry!

**Comment by paked** [comment]
@zachlatta 

burn

**Comment by jonleung** [comment]
<3

**Comment by jonleung** [comment]
THESE GIFS!!!

**Comment by jonleung** [comment]
SOOO GOOD!

Where did y'all find these?

**Pull request merged**
