### PR TITLE
Add code of conduct to club leader onboarding

### PR DESCRIPTION
**Pull request by jonleung**

### CODE REVIEW

**Comment by jonleung** [comment]
@hackclub/staff, I think this is good to merge so if this is correct, please merge it in.

I also had a question. I just wanted to double check that there isn't a better way to do make relative links between GitHub repositories:

Currently my edit adds this:

```md
- [ ] Talk about what the the [code of conduct][code-of-conduct] is and why it's
      important

[code-of-conduct]: https://github.com/hackclub/hackclub/blob/master/CONDUCT.md
```

Can I use some kind of relative link between repositories of some sort to do something like this:

```md
- [ ] Talk about what the the [code of conduct][code-of-conduct] is and why it's
      important

[code-of-conduct]: hackclub/hackclub/CONDUCT.md
```

Thanks!

**Comment by MaxWofford** [comment]
lgtm

@jonleung Can't relative link between repos on GitHub.

**Comment by zachlatta** [comment]
Yeah, it's unfortunate :-(.

That said, we do have https://gh.hackclub.io, which will allow you to use
shorter links when referring to Hack Club things.

Example usages:

- https://gh.hackclub.io (goes to root of `hackclub/hackclub`)
- https://gh.hackclub.io/workshops/README (goes to `workshops/readme` in
`hackclub/hackclub`)
- https://gh.hackclub.io/SLACK.md (goes to `SLACK.md` in
`hackclub/hackclub`)

On Sun, Jan 10, 2016 at 4:25 AM, Max Wofford <notifications@github.com>
wrote:

> lgtm
>
> @jonleung <https://github.com/jonleung> Can't relative link between repos
> on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/pull/456#issuecomment-170340999>.
>



-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by jonleung** [comment]
Ok, cool! @zachlatta is it cool if we just merge this in for now?

**Comment by zachlatta** [comment]
Yup! Merging now.

**Comment by jonleung** [comment]
<3

**Pull request merged**
