### PR TITLE
Add code of conduct meeting notes

### PR DESCRIPTION
**Pull request by jonleung**
cc @zachlatta

### CODE REVIEW

**Comment by paked** [comment]
@jonleung your tests fail :D

**Comment by jonleung** [comment]
@paked, the spelling errors that seem to make this test fail seem to be in all these other documents that have nothing to do with this pull request. I'm assuming that this is the first pull request into this repo since spellcheck was added to Markcop? Is there a way to tell Markcop to ignore those other files for now since it is not in this pull request?

Right now I don't think I have the bandwidth to fix all the spelling and grammar errors in this repository. Are there any other suggestions for what else I can do?

\cc @MaxWofford @zachlatta

**Comment by zachlatta** [comment]
I spent a bunch of time fixing all the spelling errors in #453 last night
(which @MaxWofford merged). If you rebase `master` into this pull request,
all the tests should pass.

On Thu, Jan 7, 2016 at 12:15 PM, Jonathan Leung <notifications@github.com>
wrote:

> @paked <https://github.com/paked>, the spelling errors that seem to make
> this test fail seem to be in all these other documents that have nothing to
> do with this pull request. I'm assuming that this is the first pull request
> into this repo since spellcheck was added to Markcop? Is there a way to
> tell Markcop to ignore those other files for now since it is not in this
> pull request?
>
> Right now I don't think I have the bandwidth to fix all the spelling and
> grammar errors in this repository. Are there any other suggestions for what
> else I can do?
>
> \cc @MaxWofford <https://github.com/MaxWofford> @zachlatta
> <https://github.com/zachlatta>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/pull/454#issuecomment-169793192>.
>



-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by jonleung** [comment]
<3

**Comment by MaxWofford** [comment]
I noticed the code of conduct was added to the CONTRIBUTING.md. Was this on purpose? This file mentions it should be added to the SLACK.md, but not CONTRIBUTING.md

**Comment by zachlatta** [comment]
I think it was intentional and that the code of conduct should also be
added to SLACK.md.

On Sat, Jan 9, 2016 at 6:28 PM, Max Wofford <notifications@github.com>
wrote:

> I noticed the code of conduct was added to the CONTRIBUTING.md. Was this
> on purpose? This file mentions it should be added to the SLACK.md, but not
> CONTRIBUTING.md
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/pull/454#issuecomment-170301383>.
>



-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Pull request merged**
