### PR TITLE
Add code of conduct pitching to Event Protocol

### PR DESCRIPTION
**Pull request by paked**
As spoken about in our meeting today.

### CODE REVIEW

**Comment by zachlatta** [comment]
Sorry about the failing tests, currently working on a separate pull request
to fix those.

On Thu, Jan 7, 2016 at 5:21 AM, Mention Bot <notifications@github.com>
wrote:

> By analyzing the blame information on this pull request, we identified
> @zachlatta <https://github.com/zachlatta> to be a potential reviewer
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/pull/452#issuecomment-169661418>.
>



-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by zachlatta** [comment]
And it's done! @MaxWofford merged in #453 last night, so if you rebase `master` into your branch for this pull request, all should be well.

**Comment by paked** [comment]
@zachlatta ready to merge

**Comment by zachlatta** [comment]
:heart:

**Pull request merged**
