### PR TITLE
Add Hack Strikes Back logo

### LINKED ISSUE #307: The Hack Strikes Back logo
vectorize 
the_hack_strikes_back

### PR DESCRIPTION
**Pull request by MaxWofford**
Closes #307

### CODE REVIEW

**Comment by zachlatta** [comment]
SO GOOD.

I know I keep going back and forth on this... but can we actually make the corners back to the way they were before?

tmp

and

tmp

**Comment by paked** [comment]
@zachlatta but shirts :(

**Comment by paked** [comment]
Also. I'll take 10 stickers :)

**Comment by zachlatta** [comment]
What if we did a Teespring?

_(and I may mail you some Harrison...)_

**Comment by paked** [comment]
@zachlatta That sounds awesome (:heart:). You should co-ordinate it with the re naming, to get all the hype going. (Pretty sure there would be enough people interested in shirts to warrant it, and even if it fails... Not much lost, its Teespring!)

**Comment by zachlatta** [comment]
Let's do it!

**Comment by MaxWofford** [comment]
@zachlatta Take your pick! 71477b45e0f25816add09d40288871081ecdb473

**Comment by jonleung** [comment]
@zachlatta @MaxWofford, I personally think this is the best: 64d2c9017ba6e62aaa8cd7b201dd74a01b0e040a

**Comment by MaxWofford** [comment]
@jonleung Thanks! @zachlatta, ready to merge this?

**Comment by zachlatta** [comment]
Let's go with the latest version. Can you squash the commits?

**Comment by MaxWofford** [comment]
@zachlatta Squashed!

**Comment by zachlatta** [comment]
I love it so much.

**Comment by paked** [comment]
```go
for { fmt.Println(":heart:")}
```

**Pull request merged**
