### PR TITLE
Add teacher brief for The Hack Series

### PR DESCRIPTION
**Pull request by paked**
Waiting on site link.

### CODE REVIEW

**Comment by MaxWofford** [comment]
@paked Looks like https://series.hackclub.io is up

**Comment by zachlatta** [comment]
Looks like a great first draft!

I revised it a bit. What do you think of the following?

-------------------------------------------------------------------------------

Hey!

Thanks so much for taking the time to speak with me on the phone earlier today
-- I'm from the nonprofit that called. Below are the full details for the
workshops we're running this weekend. I'd really appreciate it if you could
forward it to the teachers and ask them to announce it during class (it'd be
best if they put the website on projectors, if they have them) :-).

## The Hack Series, hosted by Hack Club

_Never written code before? Build your first website this weekend at The Hack
Series, a free workshop hosted in downtown San Francisco by Hack Club for
absolute beginners._

**Website: https://series.hackclub.io**

**Location: 1547 Mission St, San Francisco, CA 94103**

We'll be running ten 10-15 person sessions this Friday, Saturday, and Sunday.
Each session lasts 2.5 hours with a 30 minute break. Spots are limited and
filling up, so if you're interested go to our website and sign up now! It's
free.

#### What will you learn?

You'll leave the workshop with two things built:

- A personal website
- A website that calls and texts your phone

We'll also be providing you with a series of workshops to do in your free time
that'll teach you the basics of game development.

#### Who are we?

Hack Club is a San Francisco-based nonprofit that brings coding clubs to high
school around the globe. Hack Clubs are in 52 schools across 12 states and 5
countries. If you're interested in starting a club, apply at
https://hackclub.io/apply.

**Comment by paked** [comment]
> bit

;). I like your version better.

**Comment by zachlatta** [comment]
Here's a PDF to attach to the email
[hack_club_hack_series.pdf](https://github.com/hackclub/meta/files/61982/hack_club_hack_series.pdf)

**Comment by paked** [comment]
@zachlatta Not sure if we should be asking if we should be telling the teacher to sign up for a Hack Club?

**Comment by paked** [comment]
Also I'd go with 

> Hack Club is a San Francisco-based nonprofit that brings coding clubs to high school around the globe. We are in 52 schools across 12 states and 5 countries. If you're interested in starting a club, apply at https://hackclub.io/apply.

**Comment by zachlatta** [comment]
Ah, let's cut that from the teacher email (but include it in the PDF).

**Comment by paked** [comment]
@zachlatta yeah sure

**Comment by zachlatta** [comment]
Okay, let me comment a revised version (and revised PDF). One sec.

**Comment by zachlatta** [comment]
Hey!

Thanks so much for taking the time to speak with me on the phone earlier today -- I'm from the nonprofit that called. Below are the full details for the workshops we're running this weekend. I'd really appreciate it if you could forward it to the teachers and ask them to announce it during class (we've had the most success when they put the website on a projector, if they have one, and print out the below details to pass around to students (I've attached a PDF)) :-).

## The Hack Series, hosted by Hack Club

_Never written code before? Build your first website this weekend at The Hack Series, a free workshop hosted in downtown San Francisco by Hack Club for absolute beginners._

**Website: https://series.hackclub.io**

**Contact email: series@hackclub.io**

**Location: 1547 Mission St, San Francisco, CA 94103**

We'll be running ten 10-15 person sessions this Friday, Saturday, and Sunday. Each session lasts 2.5 hours with a 30 minute break. Spots are limited and filling up, so if you're interested go to our website and sign up now! It's free.

#### What will you learn?

You'll leave the workshop with two things built:

- A personal website
- A website that calls and texts your phone

We'll also be providing you with a series of workshops to do in your free time that'll teach you the basics of game development.

#### Who are we?

Hack Club is a San Francisco-based nonprofit that brings coding clubs to high school around the globe. We are in 52 schools across 12 states and 5 countries. If you're interested in starting a club, apply at https://hackclub.io/apply.
[hack_club_hack_series.pdf](https://github.com/hackclub/meta/files/61984/hack_club_hack_series.pdf)

**Comment by paked** [comment]
@zachlatta I'd also highlight that it is free

Do you want to create a PR for this? Or shall I just copy it into mine

**Comment by zachlatta** [comment]
I just made a few changes—namely adding a "How much do I need to know?" section and highlighting that it's free near the email. What are your thoughts?

**Comment by zachlatta** [comment]
Also, it'd be awesome if you could edit your PR to include this.

**Comment by paked** [comment]
@zachlatta lgtm

**Comment by zachlatta** [comment]
Awesome, here's an update PDF as well (it'd be great if you could include this in the PR).

[hack_club_hack_series.pdf](https://github.com/hackclub/meta/files/61987/hack_club_hack_series.pdf)

**Comment by zachlatta** [comment]
I made a final change to the last comment and below is the final version of the PDF.

[hack_club_hack_series.pdf](https://github.com/hackclub/meta/files/62187/hack_club_hack_series.pdf)

**Comment by paked** [comment]
@zachlatta looks ready to merge

**Pull request merged**
