### PR TITLE
Clean up folders

### PR DESCRIPTION
**Pull request by MaxWofford**

### CODE REVIEW

**Comment by zachlatta** [comment]
Why does this archive The Hack Series?

**Comment by MaxWofford** [comment]
@zachlatta Are we still actively using The Hack Series files?

**Comment by MaxWofford** [comment]
@zachlatta Just read the PR title. My bad. I'll change it.

**Comment by zachlatta** [comment]
What's the point of having an archive? I think we should either create a
folder called `events` and put it in there, leave it alone, or completely
delete it from the repo.

On Wed, Mar 9, 2016 at 6:46 AM, Max Wofford <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta> Just read the PR title. My bad.
> I'll change it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/pull/510#issuecomment-194326268>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by MaxWofford** [comment]
@zachlatta Sounds good! I'll delete the archive file.

**Comment by MaxWofford** [comment]
Before we do this, let's review https://github.com/MaxWofford/meta/pull/2

**Comment by zachlatta** [comment]
Just sent a comment over to MaxWofford#2.

On Sat, Mar 12, 2016 at 10:27 PM, Max Wofford <notifications@github.com>
wrote:

> Before we do this, let's review MaxWofford#2
> <https://github.com/MaxWofford/meta/pull/2>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/pull/510#issuecomment-195891006>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by zachlatta** [comment]
Did you mean to create a folder at events/the_hack_series/the_hack_series?

**Comment by zachlatta** [comment]
Going to go ahead and close because of the merge conflicts. I'm also not sure where this fits in relation to #512 – feel free to re-open one conflicts are resolved and that's clarified.

**Pull request closed without merging**
