### PR TITLE
Add license for modifying Amaranth

### PR DESCRIPTION
**Pull request by MaxWofford**

### CODE REVIEW

**Comment by zachlatta** [comment]
Can you fix the Markcop tests?

Two things:

- You need to rebase this repo's `master` branch into this pull request's branch (you'll probably want to rebase it into your fork's `master` as well). This'll fix the spelling error issues.
- There's a broken link in this pull request

**Comment by zachlatta** [comment]
Any updates on this?

**Comment by MaxWofford** [comment]
@zachlatta Not right now. Currently prioritizing Hack Camp.

**Comment by zachlatta** [comment]
Sounds good!

On Wed, May 11, 2016 at 1:27 PM, Max Wofford <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta> Not right now. Currently
> prioritizing Hack Camp.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/pull/552#issuecomment-218579637>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by zachlatta** [comment]
Closing due to lack of updates. Feel free to reopen with updates.

**Comment by MaxWofford** [comment]
Moved to https://github.com/hackclub/meta/pull/621

**Pull request closed without merging**
