### PR TITLE
Alt attribute added to markdown styleguide

### PR DESCRIPTION
**Pull request by MaxWofford**

### CODE REVIEW

**Comment by ad510** [comment]
All of the workshops seem to ignore this rule. And why does it help to have it? Have school internets ever blocked Hack Club images? Even if they did, is there alternate text that would meaningfully enhance the content beyond what is already in the workshop?

**Comment by paked** [comment]
@ad510 we have had a fair amount of problems with blocked content in the past. Obviously as this has not been adhered to, we need to re assess whether or not we still need it.

**Comment by jonleung** [comment]
I would opt to undo this addition because it increases the overhead of creating workshops while IMO not providing too much value.

**Comment by zachlatta** [comment]
I'm also for undoing this. Less guidelines = better, in my opinion.

On Tue, Feb 2, 2016 at 6:33 PM, Jonathan Leung <notifications@github.com>
wrote:

> I would opt to undo this addition because it increases the overhead of
> creating workshops while IMO not providing too much value.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/pull/437#issuecomment-178964282>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by jonleung** [comment]
I just submitted #488

**Pull request merged**
