### PR TITLE
Add web version of flag banner

### PR DESCRIPTION
**Pull request by jkwok91**
In preparation for HTML snippets

### CODE REVIEW

**Comment by zachlatta** [comment]
Why PNG instead of just using the SVG on the web? SVG is retina safe.

**Comment by jkwok91** [comment]
@MaxWofford previously requested png? so there are both png and svg

**Comment by MaxWofford** [comment]
Sorry, didn't mean to click merge.

**Comment by MaxWofford** [comment]
@zachlatta If you'd like the PNGs removed, we can revert the commit.

**Comment by jkwok91** [comment]
strange-clouds

**Comment by MaxWofford** [comment]
@jkwok91 that looks so good. HOW DID YOU DO IT

**Comment by zachlatta** [comment]
SO GOOD.

And yeah, let's remove the PNGs for the time being. Will make it more
difficult for people to link to an out of date version. I'll just submit a
separate pull request to remove them.

On Mon, Feb 15, 2016 at 2:34 PM, Max Wofford <notifications@github.com>
wrote:

> @jkwok91 <https://github.com/jkwok91> that looks so good. HOW DID YOU DO
> IT
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/pull/495#issuecomment-184425636>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Pull request merged**
