### PR TITLE
Update hack the future

### PR DESCRIPTION
**Pull request by MaxWofford**

### CODE REVIEW

**Comment by MaxWofford** [comment]
Derp. Will need to fix this

**Comment by zachlatta** [comment]
Hmm, not a huge fan of the gradient. I think the contrast of the black against the gradient in the letters looks nice.

What does it look like if the added edge hugged the letters tighter? Like in The Hack Strikes Back?

**Comment by jkwok91** [comment]
idk if the hack club presents is necessary in our sticker version
any way to make the outline of the letters metallic/shiny like in the original? (can stroke be gradient??)

**Comment by zachlatta** [comment]
We'll definitely want "Hack Club" somewhere on the sticker. If we're going to spend money on stickers for marketing, we probably want to put our name on them :-P.

**Comment by MaxWofford** [comment]
Anyone know why this PR isn't updating with https://github.com/hackclub/meta/pull/514/files?short_path=2b89421#diff-2b894219958d478ecefe6778dd698221

**Comment by MaxWofford** [comment]
nvm my previous comment

**Comment by zachlatta** [comment]
@MaxWofford: Have you updated this with your latest changes from the Slack? I'm ready to order stickers for this.

**Comment by MaxWofford** [comment]
I'll update this product when I have Internet (at lax right now)

**Comment by MaxWofford** [comment]
* this PR *

I see why github doesn't want me doing stuff on mobile anymore.

**Comment by MaxWofford** [comment]
So when the latest svg is opened in Inkscape it shows up, but everytime I export it nothing shows up.

oh_inkscape

**Comment by MaxWofford** [comment]
Will assign back to @zachlatta once I've sacrificed the standard number of goats to get Inkscape working again.

**Comment by zachlatta** [comment]
Closing due to lack of activity.

**Comment by zachlatta** [comment]
Feel free to reopen with any updates.

**Pull request closed without merging**
