### PR TITLE
Add license for modifying Amaranth

### PR DESCRIPTION
**Pull request by MaxWofford**

### CODE REVIEW

**Comment by zachlatta** [comment]
Still waiting on you to fix tests, @MaxWofford. Assigning you.

**Comment by MaxWofford** [comment]
@zachlatta Tests are waiting on https://github.com/hackclub/markcop/pull/115

**Comment by MaxWofford** [comment]
Assigning back to you because tests are waiting on hackclub/markcop#115

**Comment by zachlatta** [comment]
Just merged it, handing back to you.

**Comment by MaxWofford** [comment]
@zachlatta Just rebuilt the tests -- it should be good now.

**Comment by zachlatta** [comment]
Solid, sweet. Merging.

**Pull request merged**
